"""``BibFileRenderer`` — assemble ``bibliography.bib`` from a manuscript.

The :class:`BibTexEntryFormatterPort` Strategy emits one entry per
:class:`Reference`. The renderer composes them into a complete
``.bib`` file with a header comment + stable, deduplicated citation
keys.

Citation keys follow a deterministic recipe so two runs over the
same manuscript produce byte-equal ``bibliography.bib`` files
(reproducibility):

* ``<lowercase-surname-of-first-author><year><first-significant-word-of-title>``
* Stripped of accents + non-ASCII letters (``silva2024quality``).
* Collisions between two references with the same recipe append
  ``a``/``b``/``c`` suffixes.
* References without authors fall back to ``anon<year><word>``;
  without year, ``<surname>nd<word>``.

The recipe is intentionally simple and stable; sophisticated
key-generation (BibTeX's own algorithm, BibLaTeX's
``citationkey-source-list``) is overkill for our use case.
"""

from __future__ import annotations

import re
import unicodedata

from ignorantia.domain.render.entities import ManuscriptDoc, Reference
from ignorantia.domain.render.ports.bibtex_entry_formatter_port import (
    BibTexEntryFormatterPort,
    BibTexStyle,
)


class BibFileRenderer:
    """Render a manuscript's references list as a ``.bib`` file body."""

    def __init__(self, *, formatter: BibTexEntryFormatterPort) -> None:
        """Wire the renderer to one :class:`BibTexEntryFormatterPort`."""
        self._formatter = formatter

    @property
    def style(self) -> BibTexStyle:
        """Forward the formatter's :class:`BibTexStyle`."""
        return self._formatter.style

    def render(self, doc: ManuscriptDoc) -> bytes:
        """Return the ``.bib`` body as UTF-8 bytes.

        The body opens with a one-line comment naming the BibTeX
        style and the manuscript title (so a human inspecting the
        file knows what it is). Each reference becomes one entry,
        separated by a blank line.
        """
        if not doc.references:
            return self._header(doc).encode("utf-8")

        keys = generate_citation_keys(doc.references)
        entries = [
            self._formatter.format_entry(ref, key=key)
            for ref, key in zip(doc.references, keys, strict=True)
        ]
        body = "\n\n".join(entries)
        return (self._header(doc) + body + "\n").encode("utf-8")

    def _header(self, doc: ManuscriptDoc) -> str:
        return (
            f"% bibliography.bib — generated by ignorantia\n"
            f"% style: {self._formatter.style.value}\n"
            f"% manuscript: {doc.title}\n\n"
        )


def generate_citation_keys(references: tuple[Reference, ...]) -> tuple[str, ...]:
    r"""Return one citation key per reference, in input order.

    Public so callers (e.g. the LaTeX renderer that needs to insert
    ``\\cite{<key>}`` for each reference at its inline-citation
    position) get the same keys the bib-file writer used.
    """
    keys: list[str] = []
    seen: dict[str, int] = {}
    for ref in references:
        base = _base_key(ref)
        suffix_n = seen.get(base, 0)
        # suffix_n == 0 keeps the bare base; subsequent collisions get
        # 'a', 'b', 'c'… so callers can tell which entry came first.
        key = base if suffix_n == 0 else f"{base}{chr(ord('a') + suffix_n - 1)}"
        seen[base] = suffix_n + 1
        keys.append(key)
    return tuple(keys)


_WORD_RE = re.compile(r"\w+")


def _base_key(ref: Reference) -> str:
    """Generate the recipe key for ``ref`` (before collision suffixing)."""
    surname = _first_author_surname(ref.authors) or "anon"
    year = str(ref.year) if ref.year is not None else "nd"
    word = _first_significant_word(ref.title)
    return f"{surname}{year}{word}"


def _first_author_surname(authors: tuple[str, ...]) -> str:
    if not authors:
        return ""
    first = authors[0]
    surname = first.split(",", 1)[0] if "," in first else first
    return _ascii_lower(surname)


_STOP_WORDS: frozenset[str] = frozenset(
    {
        # Portuguese
        "a",
        "o",
        "as",
        "os",
        "um",
        "uma",
        "uns",
        "umas",
        "de",
        "do",
        "da",
        "dos",
        "das",
        "no",
        "na",
        "nos",
        "nas",
        "em",
        "para",
        "por",
        "com",
        "e",
        "ou",
        # English
        "the",
        "an",
        "of",
        "in",
        "on",
        "at",
        "and",
        "or",
        "to",
        "for",
    }
)


def _first_significant_word(title: str) -> str:
    """Return the first non-stopword in ``title``, ASCII-lower, or 'untitled'."""
    for token in _WORD_RE.findall(title):
        candidate = _ascii_lower(token)
        if candidate and candidate not in _STOP_WORDS:
            return candidate
    return "untitled"


def _ascii_lower(text: str) -> str:
    """Return the ASCII-lower form of ``text`` (strip accents, keep letters)."""
    decomposed = unicodedata.normalize("NFKD", text)
    only_ascii = decomposed.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-zA-Z]", "", only_ascii).lower()
