"""``_PaywallAdapter`` — base class for adapters behind a paywall.

DD-8 (v2.11.1) defined a cascade of legal mechanisms for accessing a
paid database:

1. **KEY** — vendor's official API with the user's API key.
2. **PROXY** — institutional EZproxy / SAML-bridged endpoint.
3. **FALLBACK_MD** — declarative ``citations_to_obtain.md`` listing the
   items the reviewer must retrieve manually.

In v3 the *adapter* only handles steps 1 and 2 — fetching items. The
markdown fallback is generated by a downstream service (introduced in
F5: ``ignorantia.application.use_cases.run_audit``) so the SRP boundary
is clean: an adapter knows how to fetch from one source; reporting and
manual-retrieval guidance is a separate concern.

The :class:`Method` reported by :meth:`fetch` records which step
succeeded:

* ``Method.REAL`` — KEY-mode fetch returned items.
* ``Method.REAL_PARTIAL`` — PROXY-mode fetch returned items.
* ``Method.REAL_ERROR`` — neither KEY nor PROXY produced a result.

Only network-level errors (``urllib.error.HTTPError``,
``urllib.error.URLError``, ``TimeoutError``) trigger the fall-through.
Any other exception is a subclass bug and is allowed to propagate so it
shows up loudly in tests and CI.
"""

from __future__ import annotations

from abc import abstractmethod
from urllib.error import HTTPError, URLError

from ignorantia.domain.search.entities import FetchedItem, SearchQuery, SearchResult
from ignorantia.domain.search.ports.adapter_port import AdapterPort
from ignorantia.domain.search.value_objects import Method
from ignorantia.infrastructure.http_client import HttpClient

_NETWORK_ERRORS: tuple[type[BaseException], ...] = (HTTPError, URLError, TimeoutError)


class _PaywallAdapter(AdapterPort):
    """Abstract base for paywall adapters that follow the KEY → PROXY cascade."""

    def __init__(
        self,
        http: HttpClient,
        *,
        api_key: str | None = None,
        proxy_host: str | None = None,
        max_results: int = 100,
    ) -> None:
        """Wire credentials and pagination defaults.

        Args:
            http: Shared :class:`HttpClient`.
            api_key: Vendor API key (KEY mode). ``None`` skips KEY.
            proxy_host: Institutional proxy host (PROXY mode). ``None``
                skips PROXY.
            max_results: Cap on returned items.
        """
        if max_results <= 0:
            raise ValueError("max_results must be > 0")
        self._http = http
        self._api_key = api_key
        self._proxy_host = proxy_host
        self._max_results = max_results

    def fetch(self, query: SearchQuery) -> SearchResult:
        """Run the cascade until a step succeeds; report the outcome."""
        if self._api_key is not None:
            items = self._try_step(self._key_search, query)
            if items is not None:
                return self._build_result(query, Method.REAL, items)
        if self._proxy_host is not None:
            items = self._try_proxy(query)
            if items is not None:
                return self._build_result(query, Method.REAL_PARTIAL, items)
        return self._build_result(query, Method.REAL_ERROR, ())

    @abstractmethod
    def _key_search(self, query: SearchQuery) -> tuple[FetchedItem, ...]:
        """Fetch via the vendor API. Subclasses must implement."""

    def _proxy_search(self, query: SearchQuery) -> tuple[FetchedItem, ...] | None:
        """Fetch via institutional proxy. ``None`` means unsupported.

        The default implementation returns ``None`` so an adapter that
        only supports KEY mode has zero boilerplate.
        """
        del query
        return None

    def _try_step(
        self,
        fetcher: object,
        query: SearchQuery,
    ) -> tuple[FetchedItem, ...] | None:
        try:
            return fetcher(query)  # type: ignore[no-any-return,operator]
        except _NETWORK_ERRORS:
            return None

    def _try_proxy(self, query: SearchQuery) -> tuple[FetchedItem, ...] | None:
        try:
            return self._proxy_search(query)
        except _NETWORK_ERRORS:
            return None

    def _build_result(
        self,
        query: SearchQuery,
        method: Method,
        items: tuple[FetchedItem, ...],
    ) -> SearchResult:
        return SearchResult(
            source=self.source_id,
            source_tier=self.source_tier,
            method=method,
            query=query,
            items=items,
        )
