#!/usr/bin/env python3
"""
ignorantia.render_v2 — Renderiza o HTML 4-tabs (Manuscrito/Auditoria/Dados/Venues).

Diferenças do render_manuscript.py (legacy v1):
- Layout em 4 tabs em vez de seções únicas
- Barra de cabeçalho separadora por fase (ghostwriter/honored/social)
- Integração direta com o assessor: lê avaliacao.json e popula tab Auditoria
- Sem camada Prof / sem fun_doodles (descontinuados)

Uso:
    python -m render_v2 \\
        --content manuscript-content.json \\
        --extraction extraction.csv \\
        --qa quality-appraisal.csv \\
        --searches searches.json \\
        --prisma prisma-flow.svg \\
        --assessment avaliacao.json \\
        --version 1.0.0 \\
        --topic-slug bnce-gamificacao \\
        --area "Educação" \\
        --norma "ABNT NBR 14724" \\
        --framework "PICOC" \\
        --accent "#5d4eb8" \\
        --accent-soft "#e8e3f5" \\
        --out manuscript.html
"""
from __future__ import annotations

import argparse
import csv
import html
import json
import re
import sys
from pathlib import Path
from typing import Any

# Importar visual_aids do módulo assessor
sys.path.insert(0, str(Path(__file__).parent))
from assessor.visual_aids import (
    extract_topic_keywords,
    extract_tldr_from_synthesis,
    render_tldr_cards_html,
    decorate_section,
)


def html_escape(s: str) -> str:
    return html.escape(s or "", quote=True)


def _maybe_prepend_contextual_preamble(introduction_html: str, args, content: dict,
                                         topic_kws: list) -> str:
    """F4 (v2.18.1, DD-11): se --contextual-preamble flag estiver ativa, gera
    seção 'O campo onde este artigo vive' (Wikipedia + Wikidata) e prepend ao HTML
    da Introdução. Seção é distinta da Introdução: apresenta o campo, não a pesquisa.

    Falha graciosamente se contextual_preamble.py não está disponível ou se
    fetch da Wikipedia falha — neste caso, render normal (sem preâmbulo).
    """
    if not getattr(args, "contextual_preamble", False):
        return introduction_html

    try:
        from contextual_preamble import ContextualPreamble, _mock_preamble
    except ImportError:
        # Não bloqueia render se módulo ausente
        return introduction_html

    topic = args.preamble_topic or args.topic_slug.replace("-", " ")
    area = args.preamble_area or (args.area_mae or "multi")
    # Normalizar área para chave esperada
    area_normalized = area.lower().strip()
    if area_normalized not in ContextualPreamble.AREA_TO_DISCIPLINE_MAP:
        area_normalized = "multi"
    language = args.preamble_language or "pt-BR"

    if args.preamble_mock:
        cp = _mock_preamble(topic, area_normalized, language)
    else:
        cp = ContextualPreamble(language=language)
        cp.set_topic(topic, area=area_normalized)
        try:
            cp.fetch_wikipedia_context()
            cp.fetch_wikidata_entities()
        except Exception:
            # Erros emitem warnings via WikimediaFetchWarning;
            # se tudo falhou, render_html já mostra contextual-warning.
            pass

    preamble_html = cp.render_html()
    return preamble_html + "\n" + introduction_html



def file_text(path: str | Path) -> str:
    p = Path(path)
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8", errors="ignore")


def load_json(path: str | Path) -> Any:
    p = Path(path)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def load_csv(path: str | Path) -> list[dict]:
    p = Path(path)
    if not p.exists():
        return []
    with open(p, "r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


# ── Phase banner ────────────────────────────────────────────────────────


def build_phase_banner(phase: str, version: str, lang: str = "pt-BR") -> str:
    """Constrói a barra de cabeçalho separadora por fase."""
    is_ptbr = lang.lower().startswith("pt")

    if phase == "ghostwriter":
        icon = "✍️"
        label = "FASE GHOSTWRITER" if is_ptbr else "GHOSTWRITER PHASE"
        detail = (
            "Esta versão (0.x.y) foi gerada pela IA com supervisão humana. "
            "O autor humano AINDA NÃO atestou ter cumprido as etapas que exigem "
            "juízo (leitura full-text, QA pessoal, escrita autoral da síntese). "
            "Pacote NÃO é submetível a venues — todos os venues ficam 🔴 até "
            "transição para 1.0.0."
            if is_ptbr else
            "This version (0.x.y) was generated by AI with human supervision. "
            "The human author has NOT YET attested to completing the steps "
            "requiring judgment. Package NOT submittable to venues until "
            "transition to 1.0.0."
        )
    elif phase == "honored":
        icon = "🎓"
        label = "FASE HONRADA (1.x.y)" if is_ptbr else "HONORED PHASE (1.x.y)"
        detail = (
            "Autor humano cumpriu participação substancial. Pacote pode ser "
            "submetido a venues, com avaliação real refletida nas notas. "
            "Próxima transição: 2.0.0 (revisão dupla + Cohen's kappa)."
            if is_ptbr else
            "Human author fulfilled substantial participation. Package may be "
            "submitted to venues. Next transition: 2.0.0 (dual review + kappa)."
        )
    elif phase == "social":
        icon = "🤝"
        label = "FASE SOCIAL (2.x.y)" if is_ptbr else "SOCIAL PHASE (2.x.y)"
        detail = (
            "Trabalho passou por revisão dupla independente; Cohen's kappa "
            "calculado e documentado. Pronto para submissão journal."
            if is_ptbr else
            "Work underwent independent dual review; Cohen's kappa calculated. "
            "Ready for journal submission."
        )
    else:
        icon = "❓"
        label = f"FASE {phase.upper()}"
        detail = ""

    return (
        f'<div class="phase-banner phase-{phase}">'
        f'<span class="phase-icon">{icon}</span>'
        f'<details><summary>{label} · v{html_escape(version)}</summary>'
        f'<span class="phase-detail">{html_escape(detail)}</span>'
        f'</details></div>'
    )


# ── Zone banner ─────────────────────────────────────────────────────────


def build_zone_banner(zone: str, lang: str = "pt-BR") -> str:
    """Banner que indica a zona da avaliação."""
    is_ptbr = lang.lower().startswith("pt")
    config = {
        "ok": ("🟢", "TRABALHO VÁLIDO" if is_ptbr else "VALID WORK",
               "Nenhum eliminatório falhou. As notas refletem o estado atual." if is_ptbr
               else "No eliminator failed. Scores reflect current state."),
        "incomplete": ("🟦", "TRABALHO EM CONSTRUÇÃO (POTENCIAL)" if is_ptbr
                       else "WORK IN PROGRESS (POTENTIAL)",
                       "Versão ghostwriter (0.x.y). Notas exibidas como POTENCIAL." if is_ptbr
                       else "Ghostwriter version (0.x.y). Scores shown as POTENTIAL."),
        "fraud_or_invalid": ("🟥", "TRABALHO INVÁLIDO" if is_ptbr else "INVALID WORK",
                             "Eliminatório E1-E10 falhou. Conteúdo 0.0 e Forma E forçados." if is_ptbr
                             else "Eliminator E1-E10 failed. Content 0.0 and Form E forced."),
        "invalid_content": ("🟧", "CONTEÚDO INVÁLIDO" if is_ptbr else "INVALID CONTENT",
                            "Eliminatório E12-E15 falhou. Conteúdo 0.0; Forma pode ser >E." if is_ptbr
                            else "Eliminator E12-E15 failed. Content 0.0; Form may be >E."),
    }
    icon, title, detail = config.get(zone, ("?", zone, ""))
    return (
        f'<div class="zone-banner zone-{html_escape(zone)}">'
        f'<span class="zone-banner-icon">{icon}</span>'
        f'<div class="zone-banner-body">'
        f'<strong>{html_escape(title)}</strong><br>'
        f'<span style="font-size:13px">{html_escape(detail)}</span>'
        f'</div></div>'
    )


# ── Score decomposition ─────────────────────────────────────────────────


def build_dimensions_html(dimensions: list[dict]) -> str:
    """Renderiza decomposição de C1-C7 ou F1-F4 como rows."""
    if not dimensions:
        return '<p style="color:var(--text-muted)">Decomposição não disponível.</p>'
    rows = []
    for d in dimensions:
        pct = (d["points_obtained"] / d["weight"] * 100) if d["weight"] else 0
        rows.append(
            f'<div class="score-decomp-row">'
            f'<span class="score-decomp-name"><strong>{html_escape(d["code"])}</strong> {html_escape(d["name"])}</span>'
            f'<div class="score-decomp-bar"><div class="score-decomp-bar-fill" style="width:{pct:.0f}%"></div></div>'
            f'<span class="score-decomp-points">{d["points_obtained"]:.2f}/{d["weight"]}</span>'
            f'</div>'
        )
    return "\n".join(rows)


# ── Eliminators ─────────────────────────────────────────────────────────


def build_eliminators_html(eliminators: list[dict]) -> str:
    """Renderiza tabela dos 15 eliminatórios."""
    rows = []
    for e in eliminators:
        icon = "❌" if e["failed"] else "✅"
        cls = " failed" if e["failed"] else ""
        rows.append(
            f'<div class="eliminator-row{cls}">'
            f'<span class="eliminator-icon">{icon}</span>'
            f'<div class="eliminator-name">'
            f'<strong>[{html_escape(e["code"])}]</strong> {html_escape(e["name"])} '
            f'<span style="color:var(--text-muted);font-size:12px">({html_escape(e["severity"])})</span>'
            f'<span class="eliminator-detail">{html_escape(e["detail"])}</span>'
            f'</div></div>'
        )
    return "\n".join(rows)


# ── Temperature ─────────────────────────────────────────────────────────


def build_temperature_html(temperature: dict, lang: str = "pt-BR") -> str:
    """Renderiza card de temperatura ou suprimida."""
    is_ptbr = lang.lower().startswith("pt")
    if temperature.get("suppressed"):
        title = "Temperatura suprimida" if is_ptbr else "Temperature suppressed"
        return (
            f'<div class="suppressed-temperature">'
            f'<strong>🌡️ {html_escape(title)}</strong>'
            f'<p style="margin-top:8px;font-size:13px">{html_escape(temperature.get("suppressed_reason", ""))}</p>'
            f'</div>'
        )
    value = temperature.get("value", 0.0) or 0.0
    pct = value * 100
    c7_label = "C7 ATIVO" if temperature.get("c7_available") else "C7 AUSENTE (modo standalone)"
    if not is_ptbr:
        c7_label = "C7 ACTIVE" if temperature.get("c7_available") else "C7 ABSENT (standalone)"
    crits_html = []
    for c in temperature.get("criteria", []):
        crit_pct = c["score_0_1"] * 100
        crits_html.append(
            f'<div class="temperature-criterion">'
            f'<span><strong>{html_escape(c["code"])}</strong> {html_escape(c["name"])}</span>'
            f'<span style="color:var(--text-secondary);font-family:monospace">'
            f'{c["score_0_1"]:.3f} · peso {c["weight"]:.2f}</span>'
            f'</div>'
        )
    return (
        f'<div class="temperature-card">'
        f'<div style="display:flex;justify-content:space-between;align-items:baseline">'
        f'<h3 style="margin:0">🌡️ Temperatura</h3>'
        f'<span class="temperature-value">{value:.3f}</span>'
        f'</div>'
        f'<div class="temperature-bar">'
        f'<div class="temperature-marker" style="left:{pct:.0f}%"></div>'
        f'</div>'
        f'<p style="font-size:12px;color:var(--text-muted);margin:0">{html_escape(c7_label)}</p>'
        f'<div class="temperature-criteria">'
        + "\n".join(crits_html) +
        f'</div>'
        f'<details style="margin-top:12px;font-size:13px">'
        f'<summary style="cursor:pointer;color:var(--text-secondary)">Como é calculada?</summary>'
        f'<p style="margin-top:8px;font-size:12px;color:var(--text-secondary)">'
        f'{html_escape(temperature.get("tooltip_explanation", ""))}'
        f'</p></details>'
        f'</div>'
    )


# ── Notes (críticas, importantes, polimento) ────────────────────────────


def build_notes_html(notes: dict, lang: str = "pt-BR") -> str:
    """Renderiza listagem do que falta para nota máxima."""
    is_ptbr = lang.lower().startswith("pt")
    sections = []
    for severity, label, color in [
        ("critical", "Crítico" if is_ptbr else "Critical", "var(--bad)"),
        ("important", "Importante" if is_ptbr else "Important", "var(--med)"),
        ("polish", "Polimento" if is_ptbr else "Polish", "var(--lo)"),
    ]:
        items = notes.get(severity, [])
        if not items:
            continue
        items_html = "\n".join(f'<li>{html_escape(item)}</li>' for item in items)
        sections.append(
            f'<div style="margin:16px 0">'
            f'<h4 style="color:{color};margin:0 0 8px">{label} ({len(items)})</h4>'
            f'<ul style="margin:0;font-size:13px">{items_html}</ul>'
            f'</div>'
        )
    if not sections:
        msg = "Nenhuma observação. Trabalho atende todos os critérios." if is_ptbr \
              else "No observations. Work meets all criteria."
        return f'<p style="color:var(--good)">✅ {msg}</p>'
    return "\n".join(sections)


# ── Plagiarism ──────────────────────────────────────────────────────────


def build_plagiarism_html(plagiarism: dict, lang: str = "pt-BR") -> str:
    """Renderiza relatório de plágio camada 1."""
    is_ptbr = lang.lower().startswith("pt")
    n_critical = plagiarism.get("critical_matches", 0)
    n_warning = plagiarism.get("warning_matches", 0)
    n_legitimate = plagiarism.get("legitimate_matches", 0)
    n_phrases = plagiarism.get("n_phrases_checked", 0)
    n_sources = plagiarism.get("n_sources_compared", 0)

    if n_critical == 0 and n_warning == 0:
        msg = "Nenhum match crítico ou warning detectado na camada 1." if is_ptbr \
              else "No critical or warning matches detected in layer 1."
        out = f'<p style="color:var(--good)">✅ {msg}</p>'
    else:
        out = (
            f'<p>'
            f'🔴 <strong>{n_critical}</strong> críticos · '
            f'🟡 <strong>{n_warning}</strong> avisos · '
            f'🟢 <strong>{n_legitimate}</strong> legítimos'
            f'</p>'
        )
    out += (
        f'<p style="font-size:12px;color:var(--text-muted)">'
        f'Camada 1 verificou {n_phrases} frases contra {n_sources} fontes do corpus interno. '
        f'{html_escape(plagiarism.get("advisory", ""))}'
        f'</p>'
    )
    return out


def build_sprint_badge_html(badge: dict, lang: str = "pt-BR",
                              minimal_info: dict | None = None,
                              area_mae: str | None = None) -> str:
    """Renderiza Sprint Badge com disclosure pattern acessível.

    Substitui o tooltip CSS-only (que exigia hover/focus) por um botão
    "ver detalhes" que controla um painel expansível via aria-expanded.
    Acessível em mobile e por leitores de tela.

    Args:
        badge: dict serializado por sprint_badge.serialize_badge
        lang: 'pt-BR' ou 'en'
        minimal_info: dict 'minimal_package_detected' do assessment (opcional)
        area_mae: área-mãe do tema (ex.: 'educacao', 'saude') — usado para
            adicionar aviso de heterogeneidade Qualis quando aplicável.
    """
    if not badge:
        return ""
    is_ptbr = lang.lower().startswith("pt")
    color = badge.get("color", "#9090a8")
    label_pt = badge.get("label_pt", "")
    label_en = badge.get("label_en", "")
    full_tooltip = badge.get("tooltip_pt" if is_ptbr else "tooltip_en", "")
    calibration_version = badge.get("calibration_version", "?")

    # Resumo curto: primeira frase do tooltip ou primeiros 80 chars
    summary = full_tooltip.split(".")[0] + "." if "." in full_tooltip[:120] else full_tooltip[:120]

    # Lista de ajustes
    adjs = badge.get("adjustments_applied", [])
    adj_html = ""
    if adjs:
        adj_label = "Ajustes aplicados:" if is_ptbr else "Adjustments applied:"
        items = "".join(f"<li>{html_escape(a)}</li>" for a in adjs)
        adj_html = (f'<div class="sprint-badge-adjustments">'
                    f'<strong>{adj_label}</strong><ul>{items}</ul></div>')

    # Indicador de modo pacote mínimo (Rodada O)
    minimal_indicator = ""
    if minimal_info and minimal_info.get("is_minimal"):
        signals = minimal_info.get("signals", [])
        force_mode = minimal_info.get("force_mode", "auto")
        n_signals = len(signals)
        if is_ptbr:
            mode_label = ("(forçado)" if force_mode == "yes"
                          else f"(auto-detectado por {n_signals} sinais)")
            minimal_indicator = (
                f'<div class="sprint-badge-minimal-info">'
                f'<strong>📦 Modo pacote mínimo {mode_label}</strong> — '
                f'classificação calibrada empiricamente sobre 187 SLRs reais (Rodada N). '
                f'Granularidade reduzida a 3 faixas (SUB-Q4 / Q2-Q3 / Q1) por limitações '
                f'do sinal sem texto integral. Para classificação fina (A1/A2/A3/B1), '
                f'submeta pacote completo com seções estruturadas extraídas.'
                f'</div>')
        else:
            mode_label = ("(forced)" if force_mode == "yes"
                          else f"(auto-detected via {n_signals} signals)")
            minimal_indicator = (
                f'<div class="sprint-badge-minimal-info">'
                f'<strong>📦 Minimal package mode {mode_label}</strong> — '
                f'classification empirically calibrated on 187 real SLRs (Round N). '
                f'Reduced granularity (SUB-Q4 / Q2-Q3 / Q1) due to signal limitations '
                f'without full text. For fine-grained classification (A1/A2/A3/B1), '
                f'submit complete package with structured sections.'
                f'</div>')

    # Aviso de heterogeneidade Qualis para áreas com critérios diferenciados (R2 item 8)
    area_warning = ""
    area_norm = (area_mae or "").lower().strip()
    if area_norm in ("educacao", "educação", "education"):
        if is_ptbr:
            area_warning = (
                f'<div class="sprint-badge-area-warning">'
                f'<strong>ℹ️ Área "Educação" — heterogeneidade conhecida</strong> — '
                f'a Plataforma Sucupira aplica critérios diferenciados na Educação, '
                f'com subáreas de avaliação distintas. Um mesmo periódico pode ser '
                f'classificado em estratos diferentes conforme o programa de pós-graduação '
                f'que o cita. Esta classificação automática é menos confiável aqui '
                f'(calibração separada por sub-área prevista para Rodada U).'
                f'</div>')
        else:
            area_warning = (
                f'<div class="sprint-badge-area-warning">'
                f'<strong>ℹ️ "Education" area — known heterogeneity</strong> — '
                f'CAPES Sucupira applies differentiated criteria in Education, with '
                f'distinct evaluation sub-areas. A given journal may be classified '
                f'in different strata depending on the postgraduate program citing it. '
                f'Automatic classification is less reliable here '
                f'(sub-area-specific calibration planned for Round U).'
                f'</div>')

    # Calibration version footer
    calib_label = "Calibração" if is_ptbr else "Calibration"
    calib_html = (
        f'<div style="margin-top: 10px; font-size: 10px; color: var(--text-muted);">'
        f'{calib_label}: <code>{html_escape(calibration_version)}</code>'
        f'</div>'
    )

    primary = label_pt if is_ptbr else label_en
    secondary = label_en if is_ptbr else label_pt

    details_btn_label = "ver detalhes" if is_ptbr else "view details"
    details_id = "sprint-badge-details"

    return (
        f'<div class="sprint-badge-container">'
        # Pill principal (sem tooltip CSS-only)
        f'<span class="sprint-badge" '
        f'style="--sprint-color: {color}; background: {color};" '
        f'role="status" '
        f'aria-label="{html_escape(primary)}">'
        f'<span class="sprint-badge-pt">{html_escape(primary)}</span>'
        f'<span class="sprint-badge-en">{html_escape(secondary)}</span>'
        f'</span>'
        # Botão "ver detalhes" — disclosure trigger
        f'<button type="button" class="sprint-badge-toggle" '
        f'aria-expanded="false" aria-controls="{details_id}">'
        f'{details_btn_label}'
        f'</button>'
        # Resumo curto inline (sempre visível)
        f'<div class="sprint-badge-summary">{html_escape(summary)}</div>'
        # Painel de detalhes (visível quando data-expanded=true)
        f'<div class="sprint-badge-details" id="{details_id}" data-expanded="false" role="region">'
        f'<div>{html_escape(full_tooltip)}</div>'
        f'{adj_html}'
        f'{minimal_indicator}'
        f'{area_warning}'
        f'{calib_html}'
        f'</div>'
        f'</div>'
    )


def build_audit_html(audit: dict, lang: str = "pt-BR") -> str:
    """Renderiza painel de auditoria forense (Rodada F).

    Mostra os 7 detectores A1-A7, cada um com contagem de findings e detalhes.
    """
    is_ptbr = lang.lower().startswith("pt")
    findings = audit.get("findings", [])
    counts = audit.get("by_severity", {})
    n_error = counts.get("error", 0)
    n_warning = counts.get("warning", 0)
    n_info = counts.get("info", 0)

    detector_names = {
        "A1": "DOI malformado" if is_ptbr else "Malformed DOI",
        "A2": "Citações órfãs" if is_ptbr else "Orphan citations",
        "A3": "Refs não citadas" if is_ptbr else "Uncited references",
        "A4": "IDs com gaps" if is_ptbr else "ID gaps",
        "A5": "DOIs duplicados" if is_ptbr else "Duplicate DOIs",
        "A6": "DOI/venue inconsistente" if is_ptbr else "DOI/venue mismatch",
        "A7": "Refs sem rastreabilidade" if is_ptbr else "Untraceable refs",
    }
    sev_icon = {"error": "🔴", "warning": "🟡", "info": "🔵"}

    if not findings:
        msg = "✅ Nenhum problema detectado pelos 7 detectores forenses (A1-A7)." if is_ptbr \
              else "✅ No issues detected by the 7 forensic detectors (A1-A7)."
        return f'<p style="color:var(--good)">{msg}</p>'

    # Header agregado
    summary_label = "Resumo" if is_ptbr else "Summary"
    out = [
        '<p>',
        f'🔴 <strong>{n_error}</strong> erros · ',
        f'🟡 <strong>{n_warning}</strong> avisos · ',
        f'🔵 <strong>{n_info}</strong> infos',
        '</p>',
    ]

    # Tabela de findings
    out.append('<table style="width:100%;border-collapse:collapse;margin-top:12px;font-size:13px;">')
    out.append(
        '<thead><tr style="background:var(--bg-soft);border-bottom:1px solid var(--border)">'
        f'<th style="padding:6px;text-align:left;width:60px;">{"Detector" if is_ptbr else "Detector"}</th>'
        f'<th style="padding:6px;text-align:left;width:60px;">{"Severidade" if is_ptbr else "Severity"}</th>'
        f'<th style="padding:6px;text-align:left;">{"Mensagem" if is_ptbr else "Message"}</th>'
        '</tr></thead><tbody>'
    )
    for f in findings:
        det = f.get("detector", "?")
        sev = f.get("severity", "info")
        msg = html_escape(f.get("message", ""))
        evidence = html_escape(f.get("evidence", ""))
        det_label = f"{det} · {detector_names.get(det, '')}"
        ev_html = f'<br><span style="font-size:11px;color:var(--text-muted)">{evidence}</span>' if evidence else ""
        out.append(
            '<tr style="border-bottom:1px solid var(--border)">'
            f'<td style="padding:6px;vertical-align:top;font-family:monospace;font-size:11px;">{html_escape(det_label)}</td>'
            f'<td style="padding:6px;vertical-align:top;">{sev_icon.get(sev, "")} {html_escape(sev)}</td>'
            f'<td style="padding:6px;vertical-align:top;">{msg}{ev_html}</td>'
            '</tr>'
        )
    out.append('</tbody></table>')

    # Nota explicativa sobre os 7 detectores
    note = (
        "Os 7 detectores (A1-A7) verificam integridade verificável: formato de DOI, "
        "consistência de citações, sequencialidade de IDs, duplicação, rastreabilidade. "
        "Todos rodam offline e são determinísticos."
        if is_ptbr else
        "The 7 detectors (A1-A7) verify auditable integrity: DOI format, citation "
        "consistency, ID sequencing, duplication, traceability. All run offline and "
        "are deterministic."
    )
    out.append(f'<p style="font-size:11px;color:var(--text-muted);margin-top:8px;">{note}</p>')

    return "\n".join(out)


# ── References list ─────────────────────────────────────────────────────


def build_references_list(refs: list[dict]) -> str:
    if not refs:
        return ""
    out = []
    for r in refs:
        text = r.get("citation", "") or r.get("text", "")
        doi = r.get("doi", "")
        url = r.get("url", "") or (f"https://doi.org/{doi}" if doi else "")
        link = ""
        if url:
            link = f' <a href="{html_escape(url)}" target="_blank" rel="noopener">{html_escape(url)}</a>'
        out.append(f'<li>{html_escape(text)}{link}</li>')
    return "\n".join(out)


# ── PRISMA flow ─────────────────────────────────────────────────────────


def inline_prisma_svg(svg_path: Path) -> str:
    if not svg_path.exists():
        return "<p>PRISMA flow ausente.</p>"
    svg = svg_path.read_text(encoding="utf-8")
    return re.sub(r'^<\?xml[^>]+\?>\s*', '', svg).strip()


# ── AI declaration ──────────────────────────────────────────────────────


def build_ai_declaration_html(content: dict, lang: str = "pt-BR") -> str:
    is_ptbr = lang.lower().startswith("pt")
    ai = content.get("ai_declaration") or {}
    if not ai:
        msg = "Declaração de IA ausente." if is_ptbr else "AI declaration absent."
        return f'<p style="color:var(--bad)">⚠️ {msg}</p>'
    fields = [
        ("tool", "Ferramenta" if is_ptbr else "Tool"),
        ("provider", "Provedor" if is_ptbr else "Provider"),
        ("interface", "Interface", ),
        ("stages", "Etapas" if is_ptbr else "Stages"),
        ("purpose_per_stage", "Propósito por etapa" if is_ptbr else "Purpose per stage"),
        ("human_oversight", "Supervisão humana" if is_ptbr else "Human oversight"),
        ("authors_responsible", "Autores responsáveis" if is_ptbr else "Authors responsible"),
    ]
    rows = []
    for f in fields:
        key = f[0]
        label = f[1]
        v = ai.get(key, "")
        if isinstance(v, list):
            v = "; ".join(v)
        if v:
            rows.append(f'<dt>{html_escape(label)}</dt><dd>{html_escape(str(v))}</dd>')
    return f'<dl class="ai-declaration">{"".join(rows)}</dl>'


# ── Studies table ───────────────────────────────────────────────────────


def build_studies_table(extraction_rows: list[dict], qa_rows: list[dict]) -> str:
    qa_by_id = {}
    for r in qa_rows:
        sid = r.get("id") or r.get("study_id") or ""
        score = r.get("consensus_total") or r.get("reviewer1_total") or "-"
        qa_by_id[sid] = score

    rows = []
    for r in extraction_rows:
        sid = r.get("id", "") or r.get("study_id", "")
        title = r.get("title", "")
        authors = r.get("authors", "")
        year = r.get("year", "")
        venue = r.get("venue", "")
        country = r.get("country", "") or r.get("country_authors", "")
        study_type = r.get("study_type", "") or r.get("methods", "")
        rq = r.get("rq_addressed", "")
        qa = qa_by_id.get(sid, "-")
        title_short = (title[:80] + "...") if len(title) > 80 else title
        rows.append(
            f'<tr>'
            f'<td><code>{html_escape(sid)}</code></td>'
            f'<td title="{html_escape(authors)}">{html_escape(title_short)}</td>'
            f'<td>{html_escape(str(year))}</td>'
            f'<td>{html_escape(venue)}</td>'
            f'<td>{html_escape(country)}</td>'
            f'<td>{html_escape(study_type)}</td>'
            f'<td>{html_escape(rq)}</td>'
            f'<td class="qa-cell">{html_escape(str(qa))}</td>'
            f'</tr>'
        )
    return "\n".join(rows)


# ── Venues matrix (Rodada E2) ───────────────────────────────────────────


def build_venues_matrix_html(venues_eval: dict, lang: str = "pt-BR") -> str:
    """Renderiza matriz de venues com status colorido."""
    is_ptbr = lang.lower().startswith("pt")
    if not venues_eval or not venues_eval.get("checks"):
        msg = "Avaliação por venue não disponível." if is_ptbr else "Venue evaluation unavailable."
        return f'<p style="color:var(--text-muted)">{msg}</p>'

    if venues_eval.get("phase_blocked"):
        return (
            f'<div class="zone-banner zone-incomplete">'
            f'<span class="zone-banner-icon">🟦</span>'
            f'<div class="zone-banner-body">'
            f'<strong>{html_escape(venues_eval.get("phase_message", ""))}</strong>'
            f'<p style="margin-top:8px;font-size:13px">'
            f'Listando potencial dos venues; nenhum aceitará submissão até autor humano honrar a participação.'
            f'</p></div></div>'
        )

    n_excellent = venues_eval.get("n_excellent", 0)
    n_ready = venues_eval.get("n_ready", 0)
    n_near = venues_eval.get("n_near", 0)
    n_far = venues_eval.get("n_far", 0)
    n_inadequate = venues_eval.get("n_inadequate", 0)

    summary_html = (
        f'<div style="display:flex;gap:12px;flex-wrap:wrap;margin:16px 0;font-size:14px">'
        f'<span style="background:#cce0ff;color:#1a4480;padding:6px 12px;border-radius:4px">🔵 Excelente: <strong>{n_excellent}</strong></span>'
        f'<span style="background:var(--zone-ok-bg);color:var(--zone-ok-fg);padding:6px 12px;border-radius:4px">🟢 Pronto: <strong>{n_ready}</strong></span>'
        f'<span style="background:#fff8d4;color:#8b6f1a;padding:6px 12px;border-radius:4px">🟡 Próximo: <strong>{n_near}</strong></span>'
        f'<span style="background:var(--zone-invalid-content-bg);color:var(--zone-invalid-content-fg);padding:6px 12px;border-radius:4px">🟠 Distante: <strong>{n_far}</strong></span>'
        f'<span style="background:var(--zone-invalid-bg);color:var(--zone-invalid-fg);padding:6px 12px;border-radius:4px">🔴 Inadequado: <strong>{n_inadequate}</strong></span>'
        f'</div>'
    )

    rows_html = []
    for c in venues_eval["checks"]:
        # Apenas venues 🔵, 🟢, 🟡 mostram detalhes expandidos por padrão
        # 🟠 e 🔴 ficam em <details> colapsado
        is_actionable = c["status"] in ("excellent", "ready", "near")

        # Excellence signals (só para 🔵)
        excellence_html = ""
        if c.get("excellence_signals"):
            excellence_html = "<ul style='margin:8px 0;font-size:13px;color:var(--good)'>"
            for sig in c["excellence_signals"]:
                excellence_html += f"<li>✓ {html_escape(sig)}</li>"
            excellence_html += "</ul>"

        failed_html = ""
        if c.get("failed_checks"):
            failed_html = "<ul style='margin:8px 0;font-size:13px'>"
            for f in c["failed_checks"]:
                failed_html += f"<li><strong>{html_escape(f['name'])}</strong>: {html_escape(f['detail'])}</li>"
            failed_html += "</ul>"

        url_link = ""
        if c.get("url_guidelines"):
            url_link = f' · <a href="{html_escape(c["url_guidelines"])}" target="_blank" rel="noopener">guidelines</a>'

        meta_line = (
            f'<span style="font-size:12px;color:var(--text-muted)">'
            f'{html_escape(c.get("publisher", ""))} · '
            f'Qualis {html_escape(c.get("qualis_equiv", ""))} · '
            f'{html_escape(c.get("quartil", ""))}'
            f'{url_link}'
            f'</span>'
        )

        bg_color = {
            "excellent": "#cce0ff",
            "ready": "var(--zone-ok-bg)",
            "near": "#fff8d4",
            "far": "var(--zone-invalid-content-bg)",
            "inadequate": "var(--zone-invalid-bg)",
        }.get(c["status"], "var(--bg-card)")

        if is_actionable:
            rows_html.append(
                f'<div style="border:1px solid var(--border);border-left:4px solid currentColor;'
                f'background:{bg_color};padding:12px 16px;margin:8px 0;border-radius:0 4px 4px 0">'
                f'<div style="display:flex;justify-content:space-between;align-items:center">'
                f'<strong>{c["status_icon"]} {html_escape(c["venue_name"])}</strong>'
                f'</div>'
                f'<div style="margin-top:4px">{meta_line}</div>'
                f'<p style="margin:8px 0 0;font-size:13px"><em>{html_escape(c.get("advisory", ""))}</em></p>'
                f'{excellence_html}'
                f'{failed_html}'
                f'</div>'
            )
        else:
            # Colapsa 🟠 e 🔴 em <details>
            rows_html.append(
                f'<details style="border:1px solid var(--border);background:var(--bg-card);'
                f'padding:8px 12px;margin:6px 0;border-radius:4px">'
                f'<summary style="cursor:pointer">{c["status_icon"]} '
                f'<strong>{html_escape(c["venue_name"])}</strong> '
                f'<span style="color:var(--text-muted);font-size:12px">'
                f'({len(c.get("failed_checks", []))} falha(s))</span></summary>'
                f'<div style="margin-top:8px;padding-top:8px;border-top:1px solid var(--border)">'
                f'<div>{meta_line}</div>'
                f'<p style="margin:8px 0;font-size:13px"><em>{html_escape(c.get("advisory", ""))}</em></p>'
                f'{failed_html}'
                f'</div></details>'
            )

    return summary_html + "\n".join(rows_html)


# ── Helpers ─────────────────────────────────────────────────────────────


def section_options(rqs):
    sections = [(f"sec-{i:02d}", n) for i, n in enumerate([
        "Resumo", "Introdução", "Background", "Metodologia",
        "Resultados", "Síntese", "Discussão", "Limitações",
        "Conclusão", "NÃO é", "Referências",
    ])]
    return "\n".join(
        f'<option value="{html_escape(sid)}">{html_escape(name)}</option>'
        for sid, name in sections
    )


def rq_options(rqs):
    return "\n".join(
        f'<option value="rq-{i+1}">RQ{i+1}</option>'
        for i in range(len(rqs))
    )


def replace_inline_ref_markers(html_text: str, refs: list[dict]) -> str:
    """Faz [n] → <a href="#ref-n">[n]</a>"""
    def replace(match):
        n = match.group(1)
        return f'<a href="#ref-{n}" class="cite">[{n}]</a>'
    return re.sub(r'\[(\d+)\]', replace, html_text or "")


# ── Main ────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Render HTML 4-tabs unificado")
    parser.add_argument("--content", required=True, type=Path)
    parser.add_argument("--extraction", required=True, type=Path)
    parser.add_argument("--qa", required=True, type=Path)
    parser.add_argument("--searches", default=None, type=Path)
    parser.add_argument("--prisma", required=True, type=Path)
    parser.add_argument("--assessment", default=None, type=Path,
                        help="JSON gerado por assessor.main")
    parser.add_argument("--template", default=None, type=Path,
                        help="Template HTML (default: assets/templates/manuscript-template-v2.html)")
    parser.add_argument("--version", required=True)
    parser.add_argument("--topic-slug", required=True)
    parser.add_argument("--area", default="")
    parser.add_argument("--area-mae", default="",
                        help="Área-mãe Sucupira (ex.: 'educacao', 'saude') — controla "
                             "avisos contextuais no Sprint Badge.")
    parser.add_argument("--norma", default="ABNT NBR 14724")
    parser.add_argument("--framework", default="PICO")
    parser.add_argument("--accent", default="#5d4eb8")
    parser.add_argument("--accent-soft", default="#e8e3f5")
    parser.add_argument("--out", required=True, type=Path)
    # F4 (v2.18.1): integração de contextual_preamble (DD-11)
    parser.add_argument("--contextual-preamble", action="store_true",
                        help="Inclui seção 'O campo onde este artigo vive' (Wikipedia + "
                             "Wikidata) ANTES da Introdução. Distinta da Introdução; "
                             "apresenta o campo de pesquisa para audiência leiga.")
    parser.add_argument("--preamble-topic", default=None,
                        help="Tópico para preâmbulo contextual (default: usa --topic-slug).")
    parser.add_argument("--preamble-area", default=None,
                        help="Área para preâmbulo contextual (saude|educacao|cs_se|"
                             "ciencias_sociais|humanidades|business|multi). "
                             "Default: usa --area-mae.")
    parser.add_argument("--preamble-language", default="pt-BR",
                        help="Idioma do preâmbulo (pt-BR|en-US|es-ES). Default: pt-BR.")
    parser.add_argument("--preamble-mock", action="store_true",
                        help="Usa fixtures determinísticas para preâmbulo (CI/offline).")
    args = parser.parse_args()

    content = load_json(args.content) or {}
    extraction = load_csv(args.extraction)
    qa = load_csv(args.qa)
    assessment = load_json(args.assessment) if args.assessment else {}

    # Default template path
    if args.template is None:
        # Procurar relativo ao script (portável)
        script_dir = Path(__file__).parent
        candidates = [
            script_dir.parent / "assets" / "templates" / "manuscript-template-v2.html",
            script_dir.parent / "assets" / "templates" / "manuscript-template.html",
        ]
        for c in candidates:
            if c.exists():
                args.template = c
                break
        if args.template is None:
            print(
                f"ERRO: nenhum template encontrado em {script_dir.parent / 'assets/templates/'}\n"
                f"      Esperado: manuscript-template.html ou manuscript-template-v2.html",
                file=sys.stderr,
            )
            return

    template = file_text(args.template)

    # Inline-ref expansion
    refs = content.get("references", [])
    narrative_keys = ["abstract_html", "introduction_html", "background_html",
                       "methodology_html", "results_descriptive_html",
                       "synthesis_html", "discussion_html", "threats_html",
                       "conclusion_html"]
    for k in narrative_keys:
        if content.get(k):
            content[k] = replace_inline_ref_markers(content[k], refs)

    lang = content.get("lang", "pt-BR")

    # Phase / Zone / Scores from assessment
    if assessment:
        phase = assessment.get("meta", {}).get("phase", "ghostwriter")
        zone = assessment.get("meta", {}).get("zone", "ok")
        content_score = assessment.get("content_axis", {}).get("score", 0.0)
        form_letter = assessment.get("form_axis", {}).get("letter", "E")
        form_score_internal = assessment.get("form_axis", {}).get("score_internal", 0.0)
        form_letter_meaning = assessment.get("form_axis", {}).get("letter_meaning", "")
        content_dimensions = assessment.get("content_axis", {}).get("dimensions", [])
        form_dimensions = assessment.get("form_axis", {}).get("dimensions", [])
        eliminators = assessment.get("eliminators", {}).get("all", [])
        notes = assessment.get("notes", {})
        plagiarism = assessment.get("plagiarism", {})
        temperature = assessment.get("temperature", {})
        venue_tier = assessment.get("content_axis", {}).get("recommended_venue_tier", "")
        audit = assessment.get("audit", {})
        sprint_badge = assessment.get("sprint_badge", {})
        minimal_package_info = assessment.get("minimal_package_detected", {})
    else:
        phase = "ghostwriter" if args.version.startswith("0.") else \
                "honored" if args.version.startswith("1.") else \
                "social" if args.version.startswith("2.") else "unknown"
        zone = "ok"
        content_score = 0.0
        form_letter = "E"
        form_score_internal = 0.0
        form_letter_meaning = ""
        content_dimensions = []
        form_dimensions = []
        eliminators = []
        notes = {}
        plagiarism = {}
        temperature = {"suppressed": True, "suppressed_reason": "Avaliação não executada"}
        venue_tier = ""
        audit = {}
        sprint_badge = {}
        minimal_package_info = {}

    # Build all template vars
    not_items_html = "\n".join(
        f'<li>{html_escape(item)}</li>'
        for item in content.get("not_this_version_items", [])
    )

    # Temporal summary (simple)
    years = []
    for r in extraction:
        try:
            years.append(int(str(r.get("year", "")).strip()))
        except ValueError:
            continue
    temporal_summary = (f"Período: {min(years)}-{max(years)} ({max(years)-min(years)} anos)"
                        if years else "Anos ausentes")

    venues = content.get("venues", [])
    venues_heading = "Venues sugeridos para esta versão" if lang.startswith("pt") else "Suggested venues"

    # Construir HTML da matriz de venues a partir de assessment.venues_evaluation
    venues_eval = (assessment or {}).get("venues_evaluation", {})
    venues_html = build_venues_matrix_html(venues_eval, lang)

    # Hash line
    hash_line = ""

    # ── Rodada G — keywords-tema + TLDR cards ──────────────────────
    topic_kws = extract_topic_keywords(content)
    tldrs = extract_tldr_from_synthesis(
        content.get("synthesis_html", "") or "",
        content.get("rqs", []) or [],
    )
    tldr_cards_html = render_tldr_cards_html(tldrs, lang)

    # Substitutions
    subs = {
        "LANG": html_escape(lang),
        "TITLE": html_escape(content.get("title", "")),
        "SUBTITLE": html_escape(content.get("subtitle", "")),
        "VERSION": html_escape(args.version),
        "DATE_ISO": html_escape(content.get("date_iso", "")),
        "ABSTRACT_SHORT": html_escape((content.get("abstract_html", "") or "")[:200]),
        "TOPIC_SLUG": html_escape(args.topic_slug),
        "LANG_LABEL": "pt-BR" if lang.startswith("pt") else lang,
        "NORMA": html_escape(args.norma),
        "FRAMEWORK": html_escape(args.framework),
        "AREA": html_escape(args.area),
        "ACCENT_COLOR": args.accent,
        "ACCENT_SOFT": args.accent_soft,
        "N_INCLUDED": str(len(extraction)),
        "N_SECTIONS": "11",
        "N_VENUES": str(len(venues)),
        "PHASE_BANNER_HTML": build_phase_banner(phase, args.version, lang),
        "ZONE_BANNER_HTML": build_zone_banner(zone, lang),
        "CONTENT_SCORE": f"{content_score:.1f}",
        "CONTENT_SCORE_PCT": f"{content_score * 10:.0f}",
        "CONTENT_VENUE_TIER": html_escape(venue_tier),
        "CONTENT_DIMENSIONS_HTML": build_dimensions_html(content_dimensions),
        "FORM_LETTER": html_escape(form_letter),
        "FORM_SCORE_INTERNAL": f"{form_score_internal:.2f}",
        "FORM_SCORE_INTERNAL_PCT": f"{form_score_internal * 10:.0f}",
        "FORM_LETTER_MEANING": html_escape(form_letter_meaning),
        "FORM_DIMENSIONS_HTML": build_dimensions_html(form_dimensions),
        "TEMPERATURE_HTML": build_temperature_html(temperature, lang),
        "ELIMINATORS_HTML": build_eliminators_html(eliminators),
        "NOTES_HTML": build_notes_html(notes, lang),
        "PLAGIARISM_HTML": build_plagiarism_html(plagiarism, lang),
        "AUDIT_HTML": build_audit_html(audit, lang),
        "SPRINT_BADGE_HTML": build_sprint_badge_html(sprint_badge, lang, minimal_package_info, args.area_mae),
        "TLDR_CARDS_HTML": tldr_cards_html,
        "ABSTRACT_HTML": decorate_section(content.get("abstract_html", ""), topic_kws),
        "INTRODUCTION_HTML": _maybe_prepend_contextual_preamble(
            decorate_section(content.get("introduction_html", ""), topic_kws),
            args, content, topic_kws,
        ),
        "BACKGROUND_HTML": decorate_section(content.get("background_html", ""), topic_kws),
        "METHODOLOGY_HTML": decorate_section(content.get("methodology_html", ""), topic_kws),
        "RESULTS_DESCRIPTIVE_HTML": decorate_section(content.get("results_descriptive_html", ""), topic_kws),
        "SYNTHESIS_HTML": decorate_section(content.get("synthesis_html", ""), topic_kws),
        "DISCUSSION_HTML": decorate_section(content.get("discussion_html", ""), topic_kws),
        "THREATS_HTML": decorate_section(content.get("threats_html", ""), topic_kws),
        "CONCLUSION_HTML": decorate_section(content.get("conclusion_html", ""), topic_kws),
        "NOT_THIS_VERSION_ITEMS_HTML": not_items_html,
        "REFERENCES_LIST": build_references_list(refs),
        "PRISMA_FLOW_SVG_INLINE": inline_prisma_svg(args.prisma),
        "STUDIES_TABLE_ROWS": build_studies_table(extraction, qa),
        "TEMPORAL_SUMMARY": html_escape(temporal_summary),
        "AI_DECLARATION_HTML": build_ai_declaration_html(content, lang),
        "VENUES_HEADING": html_escape(venues_heading),
        "VENUES_HTML": venues_html,
        "ZONE_LABEL": html_escape({
            "ok": "trabalho válido", "incomplete": "em construção",
            "fraud_or_invalid": "inválido", "invalid_content": "conteúdo inválido"
        }.get(zone, zone)),
        "SKILL_VERSION": "2.0.0-alpha24",
        "HASH_LINE": hash_line,
        "SECTION_OPTIONS": section_options(content.get("rqs", [])),
        "RQ_OPTIONS": rq_options(content.get("rqs", [])),
    }

    # Apply substitutions
    output = template
    for key, val in subs.items():
        output = output.replace("{{" + key + "}}", str(val))

    args.out.write_text(output, encoding="utf-8")
    print(f"Wrote {args.out}  ({len(output):,} chars)")


if __name__ == "__main__":
    main()
