#!/usr/bin/env python3
"""
render_manuscript.py — [DEPRECATED em v2.21.0] Render legacy v1 do HTML.

⚠ DEPRECATED — Este renderer é mantido apenas para compatibilidade com testes
antigos (Decisão 33: proteção de identidade do skill no AI disclosure).
Para uso normal, use:

    - `render_chunks.py` (renderer principal usado pelo pipeline_finalize.py)
    - `render_v2.py` (renderer alternativo 4-tabs com integração contextual_preamble)

Este arquivo NÃO recebe novos features (incluindo F4/B2 contextual_preamble).
Será removido em v3.0.0 ou quando os testes que o referenciam forem migrados.

---

Render the final ignorantia HTML manuscript from artifacts (v1 single-pass).

Reads:
  - manuscript-template.html (the HTML scaffolding with {{PLACEHOLDERS}})
  - manuscript-content.json   (all narrative sections, references, and metadata)
  - extraction.csv            (study-by-study extraction)
  - quality-appraisal.csv     (study-by-study QA scores)
  - searches.json             (per-database hits)
  - prisma-flow.svg           (generated by prisma_flow.py)

Writes:
  - manuscript.html  (auto-contained interactive HTML, ready for distribution)

Usage:
    python render_manuscript.py \\
        --template /path/to/manuscript-template.html \\
        --content manuscript-content.json \\
        --extraction extraction.csv \\
        --qa quality-appraisal.csv \\
        --searches searches.json \\
        --prisma prisma-flow.svg \\
        --out manuscript.html

manuscript-content.json schema (all string fields are HTML-safe; lists of refs are
the bibliography in canonical order — IEEE/Vancouver/APA/ABNT-formatted):

{
  "title": "...",
  "subtitle": "...",
  "topic_slug": "...",
  "version": "1.0.0",
  "date_iso": "2026-04-28",
  "lang": "pt-BR",
  "lang_label": "PT-BR",
  "norma": "ABNT",
  "framework": "PRISMA-2020",
  "area": "Educação",
  "accent_color": "#6b4eff",
  "accent_soft": "#e8e4ff",
  "abstract_html": "<p>...</p>",
  "introduction_html": "...",
  "background_html": "...",
  "methodology_html": "...",
  "results_descriptive_html": "...",
  "synthesis_html": "...",
  "discussion_html": "...",
  "threats_html": "...",
  "conclusion_html": "...",
  "not_this_version_items": ["<li>...</li>", ...],
  "references": [
    {"n": 1, "html": "Author A. Title. Venue. 2024.",
     "url": "https://doi.org/...", "doi": "10.xxxx/yyyy"},
    ...
  ],
  "annotations": [
    {"id": "ann-1", "anchor_selector": "#sec-02 p:nth-child(2)",
     "type": "observacao", "html": "Note: ..."},
    ...
  ],
  "rqs": ["RQ1: ...", "RQ2: ..."],
  "license": "CC-BY-4.0",
  "license_url": "https://creativecommons.org/licenses/by/4.0/",
  "zenodo_doi": "10.5281/zenodo.XXXXXXX",
  "previous_version_doi": null
}
"""
import argparse
import csv
import hashlib
import json
import re
import warnings
from pathlib import Path

# C5 (v2.22.0, auditoria #4): emite DeprecationWarning ao importar.
# render_manuscript.py é legacy v1; o caminho moderno é render_chunks.py
# (canônico) ou render_v2.py (alternativo 4-tabs). Será removido em v3.0.0.
warnings.warn(
    "render_manuscript.py é DEPRECATED desde v2.21.0. Use render_chunks.py "
    "(canônico, usado pelo pipeline_finalize) ou render_v2.py (alternativo "
    "standalone 4-tabs). Será removido em v3.0.0.",
    DeprecationWarning,
    stacklevel=2,
)


def html_escape(s):
    if s is None:
        return ""
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def qa_badge_class(score):
    """Map a QA total score to a badge class. Score range varies by instrument
    (5 for DARE/Kitchenham, 10 for hybrid). Normalize as fraction."""
    try:
        s = float(score)
    except (TypeError, ValueError):
        return "badge"
    # try to detect scale
    if s > 5:
        frac = s / 10.0
    else:
        frac = s / 5.0
    if frac >= 0.85:
        return "badge badge-qa-hi"
    if frac >= 0.70:
        return "badge badge-qa-mid"
    if frac >= 0.50:
        return "badge badge-qa-lo"
    return "badge badge-qa-bad"


def build_studies_table(extraction_rows, qa_rows):
    """Combine extraction + QA into table rows."""
    qa_by_id = {r.get("study_id"): r for r in qa_rows}
    out = []
    for r in extraction_rows:
        sid = r.get("study_id", "")
        cite = r.get("citation", "")
        year = r.get("year", "")
        venue = r.get("venue", "")
        frameworks = r.get("frameworks", "") or r.get("theoretical_framework", "")
        methods = r.get("methods", "") or r.get("study_type", "")
        rqs = r.get("rq_addressed", "")
        qa = qa_by_id.get(sid, {})
        qa_total = qa.get("consensus_total") or qa.get("reviewer1_total") or r.get("qa_score", "")
        doi = r.get("doi", "")
        # build anchor for citation
        if doi:
            href = f"https://doi.org/{doi.lstrip('https://doi.org/').lstrip('http://doi.org/')}"
            cite_html = f'<a href="{html_escape(href)}" rel="external">{html_escape(cite)}</a>'
        elif r.get("url"):
            cite_html = f'<a href="{html_escape(r["url"])}" rel="external">{html_escape(cite)}</a>'
        else:
            cite_html = html_escape(cite)
        rqs_html = " ".join(
            f'<span class="badge badge-rq">{html_escape(rq.strip())}</span>'
            for rq in re.split(r"[,;]\s*", rqs) if rq.strip()
        )
        qa_html = (f'<span class="{qa_badge_class(qa_total)}">{html_escape(qa_total)}</span>'
                   if qa_total != "" else "")
        rqs_data = ",".join(re.split(r"[,;]\s*", rqs)).lower()
        out.append(
            f'<tr data-id="{html_escape(sid)}" data-rqs="{html_escape(rqs_data)}" '
            f'data-qa="{html_escape(qa_total)}">'
            f'<td>{html_escape(sid)}</td>'
            f'<td>{cite_html}</td>'
            f'<td>{html_escape(year)}</td>'
            f'<td>{html_escape(venue)}</td>'
            f'<td>{html_escape(frameworks)}</td>'
            f'<td>{html_escape(methods)}</td>'
            f'<td>{rqs_html}</td>'
            f'<td>{qa_html}</td>'
            f'</tr>'
        )
    return "\n".join(out)


def build_references_list(refs):
    """Build the <ol> entries with clickable DOIs and anchors."""
    out = []
    for r in refs:
        n = r["n"]
        body = r["html"]  # already-formatted citation per the chosen style
        url = r.get("url") or (f"https://doi.org/{r['doi']}" if r.get("doi") else "")
        link_html = (f' <a class="ref-link doi" href="{html_escape(url)}" rel="external">↗</a>'
                     if url else "")
        out.append(f'<li id="ref-{n}">{body}{link_html}</li>')
    return "\n".join(out)


def build_ref_index_for_text(refs):
    """Return a dict {n: tooltip-text} for use in inline [n] references."""
    return {r["n"]: re.sub(r"<[^>]+>", "", r["html"]) for r in refs}


def replace_inline_ref_markers(html, refs):
    """Replace [n] markers in HTML with anchor tags + tooltips.

    Pattern: [12] or [3,4] or [3-5]. We expand sets and ranges.
    """
    by_n = {r["n"]: r for r in refs}

    def mk_link(n):
        r = by_n.get(int(n))
        if not r:
            return f"[{n}]"
        href = (r.get("url") or
                (f"https://doi.org/{r['doi']}" if r.get("doi") else f"#ref-{n}"))
        tooltip = re.sub(r"<[^>]+>", "", r["html"])
        # escape only attribute-unsafe chars
        tooltip_attr = (tooltip.replace("&", "&amp;").replace('"', "&quot;")
                        .replace("<", "&lt;").replace(">", "&gt;"))
        return (f'<a class="ref" href="{html_escape(href)}" '
                f'data-ref="{n}"><span class="tooltip">[{n}] {tooltip_attr}</span>{n}</a>')

    def expand_match(m):
        inner = m.group(1)
        parts = []
        for chunk in inner.split(","):
            chunk = chunk.strip()
            if "-" in chunk or "–" in chunk:
                a, b = re.split(r"[-–]", chunk, maxsplit=1)
                try:
                    for k in range(int(a), int(b) + 1):
                        parts.append(mk_link(k))
                except ValueError:
                    return m.group(0)
            else:
                try:
                    parts.append(mk_link(int(chunk)))
                except ValueError:
                    return m.group(0)
        return "[" + ",".join(parts) + "]"

    return re.sub(r"\[(\d+(?:\s*[,–-]\s*\d+)*)\]", expand_match, html)


def build_ai_declaration_html(content):
    """Build the mandatory AI declaration block.

    Reads content['ai_declaration'] dict with keys:
      tool, version, interface, period_start, period_end, stages (list),
      purpose_per_stage, human_oversight, authors_responsible.
    Lang defaults to content['lang'] / 'pt-BR'.
    """
    ai = content.get("ai_declaration") or {}
    lang = (content.get("lang") or "pt-BR").lower()
    is_ptbr = lang.startswith("pt")

    if is_ptbr:
        heading = "Declaração de uso de Inteligência Artificial Generativa"
        intro = ('Em conformidade com a <strong>Portaria CNPq nº 2.664/2026</strong>, art. 9, '
                 'declara-se:')
        labels = {
            "tool": "Ferramenta(s) utilizada(s)",
            "provider": "Provedor",
            "interface": "Interface / skill",
            "period": "Período de uso",
            "stages": "Etapas em que houve uso da ferramenta",
            "purpose": "Finalidade específica em cada etapa",
            "oversight": "Supervisão humana exercida",
            "responsibility": ("Os autores assumem integral responsabilidade pelo conteúdo "
                               "final, incluindo precisão factual, ausência de plágio e "
                               "adequação metodológica, ainda que parte do conteúdo tenha "
                               "sido mediada pela ferramenta declarada. A IA não está "
                               "listada como autora."),
            "authors": "Autor(es) responsável(eis)",
            "date": "Data",
        }
    else:
        heading = "Declaration of AI use"
        intro = ('In line with the <strong>COPE position on authorship and AI tools</strong> '
                 '(<a href="https://publicationethics.org/guidance/cope-position/authorship-and-ai-tools" rel="external">link</a>) '
                 'and the <strong>ICMJE Recommendations</strong> (January 2024 update, '
                 'Sections II.A.4 and IV.A.3.d), we declare:')
        labels = {
            "tool": "AI tool(s) used",
            "provider": "Provider",
            "interface": "Interface / skill",
            "period": "Period of use",
            "stages": "Stages where AI assistance was used",
            "purpose": "Specific purpose in each marked stage",
            "oversight": "Human oversight applied",
            "responsibility": ("The author(s) take full responsibility for the accuracy, "
                               "integrity, and originality of the manuscript, including any "
                               "errors or plagiarism that may have been introduced by the AI "
                               "tool. AI is not listed as an author."),
            "authors": "Author(s)",
            "date": "Date",
        }

    stages = ai.get("stages", [])
    stage_html = "".join(f"<li>{html_escape(s)}</li>" for s in stages)

    period = ""
    if ai.get("period_start") or ai.get("period_end"):
        period = f"{html_escape(ai.get('period_start',''))} → {html_escape(ai.get('period_end',''))}"

    body = f"""
<p>{intro}</p>
<dl class="ai-declaration">
  <dt>{labels['tool']}</dt><dd>{html_escape(ai.get('tool', '—'))}</dd>
  <dt>{labels['provider']}</dt><dd>{html_escape(ai.get('provider', '—'))}</dd>
  <dt>{labels['interface']}</dt><dd>{html_escape(ai.get('interface', 'algoritmo particular do autor (não-divulgado por segredo industrial) + LLM declarado acima'))}</dd>
  <dt>{labels['period']}</dt><dd>{period or '—'}</dd>
  <dt>{labels['stages']}</dt>
  <dd><ul>{stage_html or '<li>—</li>'}</ul></dd>
  <dt>{labels['purpose']}</dt><dd>{ai.get('purpose_per_stage', '—')}</dd>
  <dt>{labels['oversight']}</dt><dd>{ai.get('human_oversight', '—')}</dd>
</dl>
<p class="ai-responsibility"><strong>{labels['responsibility']}</strong></p>
<p><strong>{labels['authors']}:</strong> {html_escape(ai.get('authors_responsible', '—'))}<br>
<strong>{labels['date']}:</strong> {html_escape(content.get('date_iso', ''))}</p>
"""
    return heading, body


def build_venues_html(content):
    """Build the suggested venues section (Phase 8 deliverable, embedded in HTML).

    Reads content['venues'] = list of dicts with:
      name, publisher, issn, url, ai_policy_url, jif_or_qualis, access_model,
      cycle_weeks, fit_rationale.
    """
    venues = content.get("venues") or []
    lang = (content.get("lang") or "pt-BR").lower()
    is_ptbr = lang.startswith("pt")
    if is_ptbr:
        heading = "Venues sugeridos para submissão"
        intro = ("Sugestões de periódicos/conferências para submissão, "
                 "priorizando publishers de elite com adesão a COPE/ICMJE.")
        cols = ["Venue", "Publisher", "ISSN", "Política IA", "Indicador",
                "Acesso", "Ciclo (sem.)", "Adequação ao tema"]
    else:
        heading = "Suggested submission venues"
        intro = ("Suggested journals/conferences for submission, "
                 "prioritizing elite publishers adhering to COPE/ICMJE.")
        cols = ["Venue", "Publisher", "ISSN", "AI policy", "Indicator",
                "Access", "Cycle (wks)", "Fit"]

    if not venues:
        empty = ("Nenhum venue sugerido nesta versão." if is_ptbr
                 else "No venues suggested in this version.")
        return heading, f'<p class="meta">{empty}</p>'

    rows = []
    for v in venues:
        url = v.get("url", "")
        name_html = (f'<a href="{html_escape(url)}" rel="external">{html_escape(v.get("name", ""))}</a>'
                     if url else html_escape(v.get("name", "")))
        ai_url = v.get("ai_policy_url", "")
        ai_link = (f'<a href="{html_escape(ai_url)}" rel="external">link</a>'
                   if ai_url else "—")
        rows.append(
            "<tr>"
            f"<td>{name_html}</td>"
            f"<td>{html_escape(v.get('publisher', ''))}</td>"
            f"<td>{html_escape(v.get('issn', ''))}</td>"
            f"<td>{ai_link}</td>"
            f"<td>{html_escape(v.get('jif_or_qualis', ''))}</td>"
            f"<td>{html_escape(v.get('access_model', ''))}</td>"
            f"<td>{html_escape(v.get('cycle_weeks', ''))}</td>"
            f"<td>{html_escape(v.get('fit_rationale', ''))}</td>"
            "</tr>"
        )
    head_html = "".join(f"<th>{html_escape(c)}</th>" for c in cols)
    body = (f"<p>{intro}</p>"
            f'<div class="table-wrap"><table id="venues">'
            f"<thead><tr>{head_html}</tr></thead>"
            f"<tbody>{''.join(rows)}</tbody>"
            f"</table></div>")
    return heading, body


def build_annotations_html(annotations):
    """Build the <aside> elements for the serious annotations layer."""
    out = []
    for a in annotations:
        kind = a.get("type", "observacao").strip().lower()
        cls = f'annotation annotation-{kind}'
        anchor = a.get("anchor_selector", "")
        author = a.get("author", "Prof.")
        out.append(
            f'<aside class="{cls}" id="{html_escape(a["id"])}" '
            f'data-anchor="{html_escape(anchor)}">'
            f'<span class="annotation-author">— {html_escape(author)}</span>'
            f'{a["html"]}</aside>'
        )
    return "\n".join(out)


def build_fun_doodles_html(doodles):
    """DEPRECATED v2.8.0 — feature removida (Decisão 30).

    Mantido como stub para retrocompatibilidade com pacotes content.json antigos.
    Sempre retorna string vazia. Não consume `doodles` mesmo se fornecido.
    """
    return ""


def build_temporal_data(extraction_rows):
    counts = {}
    for r in extraction_rows:
        try:
            y = int(str(r.get("year", "")).strip())
        except ValueError:
            continue
        counts[y] = counts.get(y, 0) + 1
    return sorted([{"year": y, "n": n} for y, n in counts.items()],
                  key=lambda d: d["year"])


def build_qa_heatmap_data(qa_rows):
    """Build {studies: [{id, scores}], dimensions: ['QA1', 'QA2', ...]}.
    Detects QA1..QAN columns (consensus preferred, fallback to reviewer1)."""
    if not qa_rows:
        return {"studies": [], "dimensions": []}
    cols = qa_rows[0].keys()
    consensus_cols = sorted([c for c in cols if c.startswith("consensus_QA")])
    if consensus_cols:
        prefix = "consensus_"
        qcols = consensus_cols
    else:
        qcols = sorted([c for c in cols if c.startswith("reviewer1_QA")])
        prefix = "reviewer1_"
    dims = [c.replace(prefix, "") for c in qcols]
    studies = []
    for r in qa_rows:
        sid = r.get("study_id", "")
        if not sid:
            continue
        scores = []
        for c in qcols:
            try:
                scores.append(float(r.get(c, 0) or 0))
            except ValueError:
                scores.append(0)
        # normalize 0..1 (assuming max is 1 or 2 per question — DARE uses 0/0.5/1)
        mx = max(scores) if scores else 1
        if mx > 1:
            scores = [s / mx for s in scores]
        studies.append({"id": sid, "scores": scores})
    return {"studies": studies, "dimensions": dims}


def section_options(rqs):
    base = [
        ("sec-00", "§00 Resumo"),
        ("sec-01", "§01 Introdução"),
        ("sec-02", "§02 Background"),
        ("sec-03", "§03 Método"),
        ("sec-04", "§04 Resultados"),
        ("sec-05", "§05 Síntese"),
        ("sec-06", "§06 Discussão"),
        ("sec-07", "§07 Validade"),
        ("sec-08", "§08 Conclusão"),
        ("sec-ai-declaration", "§08.bis Declaração IA"),
        ("sec-venues", "§08.ter Venues"),
        ("sec-09", "§09 Não é"),
        ("sec-references", "§10 Referências"),
    ]
    return "\n".join(f'<option value="{v}">{html_escape(l)}</option>' for v, l in base)


def rq_options(rqs):
    return "\n".join(
        f'<option value="RQ{i+1}">{html_escape(rq)}</option>'
        for i, rq in enumerate(rqs or [])
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True)
    ap.add_argument("--content", required=True)
    ap.add_argument("--extraction", required=True)
    ap.add_argument("--qa", required=True)
    ap.add_argument("--searches", default=None)
    ap.add_argument("--prisma", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    template = Path(args.template).read_text(encoding="utf-8")
    content = json.loads(Path(args.content).read_text(encoding="utf-8"))

    with open(args.extraction, "r", encoding="utf-8") as f:
        extraction_rows = list(csv.DictReader(f))
    with open(args.qa, "r", encoding="utf-8") as f:
        qa_rows = list(csv.DictReader(f))
    n_databases = 0
    n_identified = 0
    if args.searches:
        searches = json.loads(Path(args.searches).read_text(encoding="utf-8"))
        if isinstance(searches, dict) and "per_database" in searches:
            n_databases = len(searches["per_database"])
            n_identified = sum(d.get("n_hits", 0) for d in searches["per_database"])
        elif isinstance(searches, list):
            n_databases = len(searches)
            n_identified = sum(d.get("n_hits", 0) for d in searches)

    prisma_svg = Path(args.prisma).read_text(encoding="utf-8")
    prisma_inline = re.sub(r'^<\?xml[^>]+\?>\s*', '', prisma_svg).strip()

    refs = content.get("references", [])
    annotations = content.get("annotations", [])
    fun_doodles = content.get("fun_doodles", [])

    # Inline-ref expansion in narrative sections
    narrative_keys = ["abstract_html", "introduction_html", "background_html",
                       "methodology_html", "results_descriptive_html",
                       "synthesis_html", "discussion_html", "threats_html",
                       "conclusion_html"]
    for k in narrative_keys:
        if content.get(k):
            content[k] = replace_inline_ref_markers(content[k], refs)

    # Append annotation asides at the end of body (positioned via JS using anchors)
    annotations_html = build_annotations_html(annotations)
    fun_doodles_html = build_fun_doodles_html(fun_doodles)
    ai_decl_heading, ai_decl_html = build_ai_declaration_html(content)
    venues_heading, venues_html = build_venues_html(content)

    studies_rows = build_studies_table(extraction_rows, qa_rows)
    refs_html = build_references_list(refs)

    temporal_data = build_temporal_data(extraction_rows)
    qa_heatmap_data = build_qa_heatmap_data(qa_rows)

    not_this = "\n".join(content.get("not_this_version_items", []))

    zen = content.get("zenodo_doi")
    zen_link = (f'· <a href="https://doi.org/{html_escape(zen)}">Zenodo DOI</a>' if zen else "")
    prev = content.get("previous_version_doi")
    prev_link = (f'<p>Versão anterior: <a href="https://doi.org/{html_escape(prev)}">link</a></p>'
                 if prev else "")

    # Append annotations layer to the end of methodology section (or wherever they belong)
    # Strategy: append all annotations to the bottom of the layout, JS positions them.
    # We add a hidden container at the end of conclusion_html.
    if annotations_html:
        content["conclusion_html"] = (
            (content.get("conclusion_html") or "") +
            f'\n<div class="annotations-container">\n{annotations_html}\n</div>'
        )

    # Substitutions
    subs = {
        "TITLE": html_escape(content.get("title", "")),
        "SUBTITLE": html_escape(content.get("subtitle", "")),
        "TOPIC_SLUG": html_escape(content.get("topic_slug", "")),
        "VERSION": html_escape(content.get("version", "1.0.0")),
        "DATE_ISO": html_escape(content.get("date_iso", "")),
        "LANG": html_escape(content.get("lang", "pt-BR")),
        "LANG_LABEL": html_escape(content.get("lang_label", "PT-BR")),
        "NORMA": html_escape(content.get("norma", "ABNT")),
        "FRAMEWORK": html_escape(content.get("framework", "PRISMA-2020")),
        "AREA": html_escape(content.get("area", "")),
        "ACCENT_COLOR": content.get("accent_color", "#6b4eff"),
        "ACCENT_SOFT": content.get("accent_soft", "#e8e4ff"),
        "ABSTRACT_SHORT": html_escape(re.sub(r"<[^>]+>", " ",
                                              content.get("abstract_html", ""))[:200]),
        "ABSTRACT_HTML": content.get("abstract_html", ""),
        "INTRODUCTION_HTML": content.get("introduction_html", ""),
        "BACKGROUND_HTML": content.get("background_html", ""),
        "METHODOLOGY_HTML": content.get("methodology_html", ""),
        "RESULTS_DESCRIPTIVE_HTML": content.get("results_descriptive_html", ""),
        "SYNTHESIS_HTML": content.get("synthesis_html", ""),
        "DISCUSSION_HTML": content.get("discussion_html", ""),
        "THREATS_HTML": content.get("threats_html", ""),
        "CONCLUSION_HTML": content.get("conclusion_html", ""),
        "NOT_THIS_VERSION_ITEMS": not_this,
        "PRISMA_FLOW_SVG_INLINE": prisma_inline,
        "STUDIES_TABLE_ROWS": studies_rows,
        "REFERENCES_LIST": refs_html,
        "FUN_DOODLES_HTML": fun_doodles_html,
        "AI_DECLARATION_HEADING": html_escape(ai_decl_heading),
        "AI_DECLARATION_HTML": ai_decl_html,
        "VENUES_HEADING": html_escape(venues_heading),
        "VENUES_HTML": venues_html,
        "SECTION_OPTIONS": section_options(content.get("rqs", [])),
        "RQ_OPTIONS": rq_options(content.get("rqs", [])),
        "TEMPORAL_DATA_JSON": json.dumps(temporal_data),
        "QA_HEATMAP_DATA_JSON": json.dumps(qa_heatmap_data),
        "N_DATABASES": str(n_databases),
        "N_IDENTIFIED": str(n_identified),
        "N_INCLUDED": str(len(extraction_rows)),
        "ZENODO_LINK": zen_link,
        "PREVIOUS_VERSION_LINK": prev_link,
        "LICENSE": html_escape(content.get("license", "CC-BY-4.0")),
        "LICENSE_URL": html_escape(content.get("license_url",
                                                "https://creativecommons.org/licenses/by/4.0/")),
        "HTML_HASH_SHORT": "computed-after",
    }

    out = template
    for k, v in subs.items():
        out = out.replace("{{" + k + "}}", v if v is not None else "")

    # Compute hash AFTER all substitutions, then inject
    h = hashlib.sha256(out.encode("utf-8")).hexdigest()[:12]
    out = out.replace("computed-after", h)

    Path(args.out).write_text(out, encoding="utf-8")
    print(f"Wrote {args.out}  ({len(out):,} chars, sha256:{h})")


if __name__ == "__main__":
    main()
